site_name: Well-Plate Data Generator
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    admonition:
      note: material/pencil
      danger: material/lightning-bolt
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/H-Shakeshaft/well-plate-generator
repo_name: H-Shakeshaft/well-plate-generator
