site_name: Well-Plate Data Generator
theme:
  name: material
  icon:
    admonition:
      note: material/pencil
      danger: material/lightning-bolt
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

